In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

In [4]:
a=np.array([[1,2,3,4],[4,5,6,7]])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [7]:
np.array([11,23,24], dtype="float")

array([11., 23., 24.])